// <auto-generated />
namespace Maarfa.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Select_All_Tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Select_All_Tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201701051355160_Select_All_Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
